apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: request
  name: request
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: request
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: request
    spec:
      containers:
        - env:
            - name: QUARKUS_DATASOURCE_DB_KIND
              value: postgresql
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: jdbc:postgresql://requestdb.default.svc.cluster.local:5432/request
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: passwd
            - name: QUARKUS_DATASOURCE_USERNAME
              value: user
            - name: QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION
              value: drop-and-create
            - name: QUARKUS_RABBITMQCLIENT_HOSTNAME
              value: rabbitmq.default.svc.cluster.local
            - name: QUARKUS_RABBITMQCLIENT_PORT
              value: "5672"
            - name: QUARKUS_RABBITMQCLIENT_VIRTUAL_HOST
              value: /
          image: dyotamo/saga-experiment-user-request-service:1.0.0
          name: request
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
