version: "3.8"

services:
  requestdb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=user
      - POSTGRES_DB=request

  profiledb:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=passwd
      - POSTGRES_USER=user
      - POSTGRES_DB=profile

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1080:1080"

  request:
    image: dyotamo/saga-experiment-user-request-service:1.0.0
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=passwd
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://requestdb:5432/request
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
      - QUARKUS_RABBITMQCLIENT_VIRTUAL_HOST=/
      - QUARKUS_RABBITMQCLIENT_HOSTNAME=rabbitmq
      - QUARKUS_RABBITMQCLIENT_PORT=5672

  profile:
    image: dyotamo/saga-experiment-user-profile-service:1.0.0
    environment:
      - QUARKUS_DATASOURCE_DB_KIND=postgresql
      - QUARKUS_DATASOURCE_USERNAME=user
      - QUARKUS_DATASOURCE_PASSWORD=passwd
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://profiledb:5432/profile
      - QUARKUS_HIBERNATE_ORM_DATABASE_GENERATION=drop-and-create
      - QUARKUS_RABBITMQCLIENT_VIRTUAL_HOST=/
      - QUARKUS_RABBITMQCLIENT_HOSTNAME=rabbitmq
      - QUARKUS_RABBITMQCLIENT_PORT=5672

  account:
    image: dyotamo/saga-experiment-user-account-service:1.0.0
    environment:
      - QUARKUS_RABBITMQCLIENT_VIRTUAL_HOST=/
      - QUARKUS_RABBITMQCLIENT_HOSTNAME=rabbitmq
      - QUARKUS_RABBITMQCLIENT_PORT=5672

  notification:
    image: dyotamo/saga-experiment-user-notification-service:1.0.0
    environment:
      - QUARKUS_RABBITMQCLIENT_VIRTUAL_HOST=/
      - QUARKUS_RABBITMQCLIENT_HOSTNAME=rabbitmq
      - QUARKUS_RABBITMQCLIENT_PORT=5672
      - QUARKUS_MAILER_HOST=mailcatcher